name: CI

on:
  workflow_dispatch:

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: "./build/web"
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: "./build/app/outputs/apk/release/app-release.apk"
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Gen certificates and profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates/
          # cat filename | base64 -w 0
          echo ${{ secrets.P12_BASE64 }} | base64 -D > ~/Library/MobileDevice/Certificates/certificate.p12
          echo ${{ secrets.MOBILEPROVISION_BASE64 }} | base64 -D > ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision
          md5 ~/Library/MobileDevice/Certificates/certificate.p12
          md5 ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision
      #install the necessary dependencies
      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install python dependencies
        run:  python -m pip install codemagic-cli-tools
      - name: Initialize Keychain with certificate
        run: |
          keychain initialize
          keychain add-certificates --certificate ~/Library/MobileDevice/Certificates/certificate.p12 --certificate-password ${{ secrets.cert_password }}
      - run: xcode-project use-profiles
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
      - run: flutter build ipa
      - run: ls ios/ 
      #- run: xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release
      - run: find . -name "*.ipa"
      - run: mkdir -p pyload
      - run: cp -af ./build/ios/iphoneos/Runner.app pyload/
      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: "./pyload"
      
